# Parameter- and classification-recovery study for multilpa().
#
# Data are generated by simulab::simulate_multilpa(), which draws the
# nonparametric two-level mixture of Vermunt (2003): clusters belong to latent
# group classes, a group class fixes profile prevalence inside its clusters,
# and one measurement model is shared by every group. That is exactly the model
# multilpa() estimates, so the generating values are the estimation target.
#
# Truth and estimates are compared by simulab::validate_recovery(). Mixture
# labels are arbitrary, so the estimated profiles and group classes are matched
# to the generating ones before anything is compared; the matching is an
# exhaustive search over permutations, which is exact for the sizes used here.
#
# Run from the project root:
#   Rscript validation/simulab-recovery/recovery-study.R

suppressMessages(pkgload::load_all(".", quiet = TRUE))
library(simulab)

# simulab 0.4.3 exports the generator as `simulate_ml_lpa()`. This script was
# written against a build that called it `simulate_multilpa()`; the signature is
# unchanged, only the name.
stopifnot(
  "simulab must provide simulate_ml_lpa(); install the sibling simulab >= 0.4.3" =
    exists("simulate_ml_lpa", mode = "function")
)

# ---------------------------------------------------------------- design ----

indicator_names <- c("reading", "maths", "science", "writing")

true_means <- matrix(
  c(-1.3, -1.1, -1.2, -0.9,
     0.0,  0.3,  0.1,  0.2,
     1.3,  1.1,  1.2,  0.9),
  nrow = 3L, byrow = TRUE, dimnames = list(NULL, indicator_names)
)

# Cluster classes differ only in how common each profile is inside them. Class 1
# is dominated by the low profile, class 2 by the high profile, and the middle
# profile is equally common in both, so the classes are not simply a relabelled
# copy of the profiles.
true_prevalence <- matrix(
  c(0.60, 0.30, 0.10,
    0.10, 0.30, 0.60),
  nrow = 2L, byrow = TRUE
)

true_class_proportions <- c(0.5, 0.5)

conditions <- list(
  list(label = "60 clusters x 20", clusters = 60L, cluster_size = 20L,
       n_starts = 20L, simulation_seed = 10000L, fit_seed = 20000L),
  list(label = "30 clusters x 10", clusters = 30L, cluster_size = 10L,
       n_starts = 20L, simulation_seed = 30000L, fit_seed = 40000L)
)

replications <- 100L
enumeration_replications <- 25L
tolerance <- 0.1

# --------------------------------------------------------------- helpers ----

## All permutations of seq_len(k), one per row.
.permutations <- function(k) {
  stopifnot("`k` must be a single positive whole number" =
              is.numeric(k) && length(k) == 1L && k >= 1 && k == as.integer(k))
  k <- as.integer(k)
  if (k == 1L) return(matrix(1L, 1L, 1L))
  smaller <- .permutations(k - 1L)
  do.call(rbind, lapply(seq_len(k), function(value) {
    rest <- matrix(setdiff(seq_len(k), value)[smaller], nrow = nrow(smaller))
    cbind(value, rest, deparse.level = 0L)
  }))
}

## Pivot a tidy accessor table back into the matrix the model parameterizes,
## with rows and columns in a stated order rather than whatever order the
## accessor happened to emit.
.as_parameter_matrix <- function(table, value, row, column, columns) {
  wide <- stats::xtabs(stats::reformulate(c(row, column), response = value),
                       data = table)
  result <- matrix(wide[, columns], nrow = nrow(wide),
                   dimnames = list(NULL, columns))
  stopifnot("the accessor must supply one value per cell" = !anyNA(result))
  result
}

.estimated_means <- function(fit, indicators) {
  .as_parameter_matrix(get_results(fit, "profiles"),
                       "mean", "profile", "indicator", indicators)
}

.estimated_sds <- function(fit, indicators) {
  .as_parameter_matrix(get_results(fit, "profiles"),
                       "standard_deviation", "profile", "indicator", indicators)
}

.estimated_prevalence <- function(fit) {
  probabilities <- get_results(fit, "profile_probabilities")
  .as_parameter_matrix(probabilities, "probability", "group_class", "profile",
                       as.character(sort(unique(probabilities$profile))))
}

.estimated_class_proportions <- function(fit) {
  probabilities <- get_results(fit, "profile_probabilities")
  averaged <- aggregate(group_class_probability ~ group_class,
                        data = probabilities, FUN = mean)
  averaged$group_class_probability
}

## The permutation of the estimated labels that sits closest to the generating
## parameters, by summed squared difference.
.best_permutation <- function(estimated, truth) {
  stopifnot("estimated and true parameters must have the same shape" =
              identical(dim(estimated), dim(truth)))
  candidates <- .permutations(nrow(truth))
  cost <- apply(candidates, 1L, function(order) {
    sum((estimated[order, , drop = FALSE] - truth)^2)
  })
  candidates[which.min(cost), ]
}

## Profiles are matched on the measurement model, which is shared by every
## group class; group classes are then matched on profile prevalence, read
## in the profile order just fixed.
.align_fit <- function(fit, indicators, means, prevalence) {
  profile_order <- .best_permutation(.estimated_means(fit, indicators), means)
  aligned <- .estimated_prevalence(fit)[, profile_order, drop = FALSE]
  list(profile_order = profile_order,
       class_order = .best_permutation(aligned, prevalence))
}

.term_table <- function(values, quantity, rows, columns) {
  index <- expand.grid(row = rows, column = columns, stringsAsFactors = FALSE)
  data.frame(term = sprintf("%s[%s, %s]", quantity, index$row, index$column),
             estimate = as.vector(values), stringsAsFactors = FALSE)
}

.estimates_frame <- function(fit, indicators, alignment) {
  profiles <- alignment$profile_order
  classes <- alignment$class_order
  profile_names <- sprintf("Profile %d", seq_along(profiles))
  class_names <- sprintf("Class %d", seq_along(classes))
  prevalence <- .estimated_prevalence(fit)[classes, profiles, drop = FALSE]
  rbind(
    .term_table(.estimated_means(fit, indicators)[profiles, , drop = FALSE],
                "mean", profile_names, indicators),
    .term_table(.estimated_sds(fit, indicators)[profiles, , drop = FALSE],
                "sd", profile_names, indicators),
    .term_table(prevalence, "probability", class_names, profile_names),
    data.frame(term = sprintf("class proportion[%s]", class_names),
               estimate = .estimated_class_proportions(fit)[classes],
               stringsAsFactors = FALSE)
  )
}

## The truth is read back out of the simulation rather than retyped, so the
## comparison cannot drift away from what was actually generated.
.truth_frame <- function(simulation) {
  parameters <- as.data.frame(simulation, what = "parameters")
  probabilities <- as.data.frame(simulation, what = "profile_probabilities")
  proportions <- aggregate(cluster_class_proportion ~ cluster_class,
                           data = probabilities, FUN = mean)
  rbind(
    data.frame(term = sprintf("mean[%s, %s]", parameters$profile, parameters$variable),
               truth = parameters$mean, stringsAsFactors = FALSE),
    data.frame(term = sprintf("sd[%s, %s]", parameters$profile, parameters$variable),
               truth = parameters$sd, stringsAsFactors = FALSE),
    data.frame(term = sprintf("probability[%s, %s]", probabilities$cluster_class,
                              probabilities$profile),
               truth = probabilities$probability, stringsAsFactors = FALSE),
    data.frame(term = sprintf("class proportion[%s]", proportions$cluster_class),
               truth = proportions$cluster_class_proportion, stringsAsFactors = FALSE)
  )
}

## `assignments()` is the verb that owns this alignment: one row per input
## individual, in input order, carrying the assigned profile and the group
## class. It replaces reading `what = "posteriors"`, which since the public
## returns were tidied is one row per individual *and profile* -- three times
## as many rows as individuals -- and so silently failed the row-count check.
.classification_accuracy <- function(fit, simulation, alignment) {
  assigned <- get_results(fit, "assignments")
  data <- as.data.frame(simulation)
  clusters <- as.data.frame(simulation, what = "clusters")
  stopifnot(
    "assignments must be one row per input individual, in input order" =
      nrow(assigned) == nrow(data) && identical(assigned$cluster, data$cluster),
    "assignments must cover every generated cluster" =
      setequal(assigned$cluster, clusters$cluster)
  )
  assigned_profile <- sprintf("Profile %d",
                              match(assigned$profile, alignment$profile_order))
  assigned_class <- sprintf("Class %d",
                            match(assigned$group_class, alignment$class_order))
  # One row per cluster for the group-level accuracy: the cluster's class is
  # constant within it, so the first row of each cluster carries it.
  first_of_cluster <- !duplicated(assigned$cluster)
  true_class <- clusters$cluster_class[match(assigned$cluster[first_of_cluster],
                                             clusters$cluster)]
  data.frame(
    individual_accuracy = mean(assigned_profile == data$profile),
    group_accuracy = mean(assigned_class[first_of_cluster] == true_class)
  )
}

.entropy_values <- function(fit) {
  entropy <- get_results(fit, "entropy")
  values <- setNames(entropy$relative_entropy, entropy$level)
  data.frame(individual_entropy = unname(values["individuals"]),
             group_entropy = unname(values["groups"]))
}

.simulate_condition <- function(replication, condition) {
  simulate_ml_lpa(
    clusters = condition$clusters, cluster_size = condition$cluster_size,
    means = true_means, profile_probabilities = true_prevalence,
    cluster_class_proportions = true_class_proportions,
    seed = condition$simulation_seed + replication
  )
}

.replicate_recovery <- function(replication, condition) {
  simulation <- .simulate_condition(replication, condition)
  fit <- multilpa(
    as.data.frame(simulation), vars = indicator_names, id = "cluster",
    n_profiles = nrow(true_means), n_group_classes = nrow(true_prevalence),
    n_starts = condition$n_starts, seed = condition$fit_seed + replication
  )
  alignment <- .align_fit(fit, indicator_names, true_means, true_prevalence)
  recovery <- validate_recovery(
    .estimates_frame(fit, indicator_names, alignment),
    .truth_frame(simulation), tolerance = tolerance
  )
  diagnostics <- data.frame(
    condition = condition$label, replication = replication,
    converged = fit$converged, boundary = fit$boundary,
    best_replicated = fit$n_best_replicated,
    log_likelihood = fit$log_likelihood,
    .entropy_values(fit),
    .classification_accuracy(fit, simulation, alignment),
    stringsAsFactors = FALSE
  )
  if (replication %% 25L == 0L) {
    message(sprintf("  %s: %d replications done", condition$label, replication))
  }
  list(recovery = data.frame(condition = condition$label,
                             replication = replication, recovery,
                             stringsAsFactors = FALSE),
       diagnostics = diagnostics)
}

## Stack one named table out of a list of replication results.
.combine <- function(runs, table) {
  do.call(rbind, lapply(runs, function(run) run[[table]]))
}

.run_condition <- function(condition) {
  message(sprintf("Condition %s: %d replications", condition$label, replications))
  runs <- lapply(seq_len(replications), .replicate_recovery, condition = condition)
  list(recovery = .combine(runs, "recovery"),
       diagnostics = .combine(runs, "diagnostics"))
}

## Which (profiles, classes) pair the information criteria select, on the same
## datasets the parameter study used.
.enumerate_replication <- function(replication, condition) {
  simulation <- .simulate_condition(replication, condition)
  candidates <- enumerate_classes(
    as.data.frame(simulation), vars = indicator_names, id = "cluster",
    n_profiles = 2:4, n_group_classes = 1:3, n_starts = 6L,
    seed = condition$fit_seed + replication
  )
  table <- as.data.frame(candidates)
  selected <- function(criterion) {
    best <- table[which.min(table[[criterion]]), , drop = FALSE]
    data.frame(criterion = criterion, n_profiles = best$n_profiles,
               n_group_classes = best$n_group_classes,
               stringsAsFactors = FALSE)
  }
  choices <- do.call(rbind, lapply(c("aic", "bic_groups", "bic_individual",
                                     "sabic_individual", "caic_individual",
                                     "icl_individual"), selected))
  data.frame(condition = condition$label, replication = replication, choices,
             correct = choices$n_profiles == nrow(true_means) &
               choices$n_group_classes == nrow(true_prevalence),
             all_converged = all(table$converged), stringsAsFactors = FALSE)
}

# ------------------------------------------------------------- summaries ----

.parameter_summary <- function(recovery) {
  averages <- aggregate(cbind(estimate, truth, bias, absolute_error) ~ condition + term,
                        data = recovery, FUN = mean)
  names(averages) <- c("condition", "term", "mean_estimate", "truth", "bias",
                       "mean_absolute_error")
  squared <- aggregate(bias ~ condition + term, data = recovery,
                       FUN = function(value) sqrt(mean(value^2)))
  names(squared) <- c("condition", "term", "rmse")
  rate <- aggregate(recovered ~ condition + term, data = recovery, FUN = mean)
  names(rate) <- c("condition", "term", "within_tolerance")
  merge(merge(averages, squared, by = c("condition", "term")), rate,
        by = c("condition", "term"))
}

.quantity_summary <- function(recovery) {
  recovery$quantity <- sub("\\[.*$", "", recovery$term)
  averages <- aggregate(cbind(bias, absolute_error, recovered) ~ condition + quantity,
                        data = recovery, FUN = mean)
  names(averages) <- c("condition", "quantity", "mean_bias", "mean_absolute_error",
                       "within_tolerance")
  squared <- aggregate(bias ~ condition + quantity, data = recovery,
                       FUN = function(value) sqrt(mean(value^2)))
  names(squared) <- c("condition", "quantity", "rmse")
  merge(averages, squared, by = c("condition", "quantity"))
}

.diagnostics_summary <- function(diagnostics) {
  averages <- aggregate(cbind(converged, boundary, individual_entropy, group_entropy,
                              individual_accuracy, group_accuracy) ~ condition,
                        data = diagnostics, FUN = mean)
  names(averages) <- c("condition", "converged", "boundary", "individual_entropy",
                       "group_entropy", "individual_accuracy", "group_accuracy")
  worst <- aggregate(cbind(individual_accuracy, group_accuracy) ~ condition,
                     data = diagnostics, FUN = min)
  names(worst) <- c("condition", "worst_individual_accuracy", "worst_group_accuracy")
  merge(averages, worst, by = "condition")
}

# ------------------------------------------------------------------- run ----

started <- Sys.time()
runs <- lapply(conditions, .run_condition)
recovery <- .combine(runs, "recovery")
diagnostics <- .combine(runs, "diagnostics")

message(sprintf("Enumeration: %d replications per condition", enumeration_replications))
enumeration <- do.call(rbind, lapply(conditions, function(condition) {
  do.call(rbind, lapply(seq_len(enumeration_replications), .enumerate_replication,
                        condition = condition))
}))
enumeration_summary <- aggregate(correct ~ condition + criterion, data = enumeration,
                                 FUN = mean)
names(enumeration_summary) <- c("condition", "criterion", "selects_true_model")
elapsed <- difftime(Sys.time(), started, units = "mins")

stopifnot(
  "every replication must contribute one row per term" =
    nrow(recovery) == 2L * replications * 32L,
  "no term may go unmatched between estimates and truth" = !anyNA(recovery$bias)
)

cat("\n=== Fit diagnostics, averaged over replications ===\n")
print(.diagnostics_summary(diagnostics), digits = 4)

cat("\n=== Recovery by quantity ===\n")
print(.quantity_summary(recovery), digits = 3)

cat("\n=== Recovery term by term ===\n")
print(.parameter_summary(recovery), digits = 3)

cat("\n=== Structure selected by each information criterion ===\n")
print(enumeration_summary, digits = 3)

cat("\n=== Modal structure chosen, by criterion ===\n")
print(aggregate(replication ~ condition + criterion + n_profiles + n_group_classes,
                data = enumeration, FUN = length))

dir.create("tmp", showWarnings = FALSE)
write.csv(recovery, file.path("tmp", "simulab-recovery-terms.csv"), row.names = FALSE)
write.csv(diagnostics, file.path("tmp", "simulab-recovery-diagnostics.csv"), row.names = FALSE)
write.csv(enumeration, file.path("tmp", "simulab-recovery-enumeration.csv"), row.names = FALSE)
saveRDS(list(recovery = recovery, diagnostics = diagnostics, enumeration = enumeration,
             means = true_means, prevalence = true_prevalence,
             class_proportions = true_class_proportions, elapsed = elapsed,
             session = sessionInfo()),
        file.path("tmp", "simulab-recovery-study.rds"))

cat(sprintf("\nReplications: %d per condition; enumeration on %d. Elapsed: %.1f minutes.\n",
            replications, enumeration_replications, as.numeric(elapsed)))
