# The `srl` data set: psychnets::SRL_GPT with descriptive column names.
#
# Five Motivated Strategies for Learning Questionnaire (MSLQ) construct scores
# for 300 simulated respondents, each the mean of the construct's Likert items
# (1-7). The responses were generated by GPT in Saqr (2025), Computers in
# Human Behavior, 173, 108769, and sampled for psychnets by
# psychnets/data-raw/SRL.R (seed 2025). They are simulated, not collected from
# students.
srl <- psychnets::SRL_GPT
names(srl) <- c(CSU = "cognitive_strategies", IV = "intrinsic_value",
                SE = "self_efficacy", SR = "self_regulation",
                TA = "test_anxiety")[names(srl)]
stopifnot(nrow(srl) == 300L, ncol(srl) == 5L, !anyNA(srl))
usethis::use_data(srl, overwrite = TRUE, compress = "xz")
